name: Release
on:
  push:
    branches: [dev]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: pretest
        run: |
          npm run pretest
          npm run test:coverage

  release:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/dev' }}
    needs: [prerelease]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: DEV RELEASE Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ env.RELEASE }}
        run: npm run semantic-release
